services:
  muse-notification:
    build: .
    container_name: Muse-notification
    depends_on:
      - postgres-notification
    environment:
      DB_URL: postgres-notification:5432/notifications
      AUTH_SERVER_URL: http://keycloak:8080
      SPRING_KAFKA_BOOTSTRAP-SERVERS: broker:29092
      NOTIFICATIONS-TOPIC: notifications
    volumes:
      - maven:/root/.m2
    ports:
      - "81:81"
    command: mvn spring-boot:run

  postgres-notification:
    container_name: Postgres-notification
    image: postgres
    environment:
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: boot
      POSTGRES_DB: notifications
    ports:
      - 5433:5432

networks:
  default:
    external: true
    name: muse-network

volumes:
  maven:
    driver: local