replicaCount: 1

spring:
  profile: dev

image:
  repository: change/me
  tag: "latest"
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: gitlab-registry-secret-notifications

kafka:
  boostrapServers: kafka.kafka.svc.cluster.local:9092
  topic: notifications

service:
  type: ClusterIP
  port: 81

postgres:
  host: notifications-postgresql.notifications.svc.cluster.local
  port: 5432
  database: muse
  url: notifications-postgresql.notifications.svc.cluster.local:5432/notifications
  user: spring

issuer:
  uri:  http://keycloak.keycloak.svc.cluster.local:8080/realms/users-auth

resources: {}

ingress:
  enabled: true
  className: nginx
  tls:
    - hosts:
        - muse.innoca.local
      secretName: muse-frontend-tls
  hosts:
    - host: muse.innoca.local
      paths:
        - path: /changeme
          pathType: Prefix
          service:
            name: ""
            port: 8080