CREATE TABLE answer_notifications(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    parent_id BIGINT NOT NULL,
    answer_id BIGINT NOT NULL,
    for_author BOOLEAN NOT NULL,
    created TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE comment_notifications(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    post_id BIGINT NOT NULL,
    comment_id BIGINT NOT NULL,
    for_author BOOLEAN NOT NULL,
    created TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE tag_post_notifications(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    post_id BIGINT NOT NULL,
    tag_name VARCHAR NOT NULL,
    created TIMESTAMPTZ NOT NULL DEFAULT now()
);