package ru.t1.debut.muse_notification.dto;

public enum EventType {
    NEW_ANSWER_FOR_POST,
    NEW_ANSWER_FOR_YOUR_POST,
    NEW_POST_FOR_TAG,
    NEW_COMMENT_FOR_POST,
    NEW_COMMENT_FOR_YOUR_POST,
    MODERATOR_EDIT_YOUR_QUESTION,
    MODERATOR_EDIT_YOUR_ANSWER,
    MODERATOR_DELETE_YOUR_QUESTION,
    MODERATOR_DELETE_YOUR_ANSWER,
    MODERATOR_EDIT_YOUR_COMMENT,
    MODERATOR_DELETE_YOUR_COMMENT,
}
